### ISSUE TITLE
onStateChanged missing from addStarMenu

### ISSUE THREAD

**Issue by Paul-Todd** [alnitak/flutter_star_menu#11]
Hi,

I noticed addStarMenu does not have a onStateChanged param so its not possible to monitor the menu state.

Workaround to use other format

**Comment by alnitak** [comment]
Hi,

you're right, when I added the addStarMenu extension, maybe I thought I'd leave it as slim as possible. But maybe it is better to have all the StarMenu parameters.
Now I have added also the [lazyItems] parameter.
It is already updated here on GitHub, I will update also pub.dev
