### ISSUE TITLE
'example/' is out-of-date

### ISSUE THREAD

**Issue by jdar** [alnitak/flutter_star_menu#12]
In the latest commit, the example/ folder was not harmonized with the code. 
Commit 49e6b5630 "added lazyItems and onStateChanged parameters to addStarMenu extension"

Under this last commit the example shows a syntax error:
"4 positional argument(s) expected, but 2 found.
Try adding the missing"

Rolling back to 3.1.0+1 has the expected signature, BUT one change is still required, in order to build correctly:
`<activity
    android:exported="true"`

 With that, it now builds and displays correctly. Tested on Android 12.

**Comment by alnitak** [comment]
Hi @jdar,

thank you for pointing me to this issue!
Due to the last changes, I had to make all the [addStarMenu] mixin parameter optionals.
I have just fixed in the repo, but this means a breaking change. You now need to name all the parameters like this:
```
.addStarMenu(
    items: items, 
    params: StarMenuParameters.dropdown(context),
    ...
),```
