### ISSUE TITLE
Please use change major version when adding breaking changes into the code

### ISSUE THREAD

**Issue by chester23491** [alnitak/flutter_star_menu#20]
Hi @alnitak 

Thank you sincerely for your valuable contribution to the Flutter community! Today, I came across an issue with the latest version `3.1.8`. It seems there's a breaking change, but the patch number was incremented in the versioning, leading to an automatic update by Flutter. To ensure smoother updates in the future, may I suggest incrementing the major number when introducing a breaking change?

Would it be possible to release version `4.0.0` instead of `3.1.8`? This would align better with the nature of the changes.

Once you've had a chance to review this, feel free to close the issue. Your attention to this matter is greatly appreciated. Thank you again!

**Comment by alnitak** [comment]
Ouch! Bad mistake, thank you!

I have updated version 3 to 3.1.9 without the breaking change on pub.dev and also published the v4!
