### ISSUE TITLE
Cannot get renderObject of inactive element

### ISSUE THREAD

**Issue by ofbozkurt** [alnitak/flutter_star_menu#21]
Hello. I'm using flutter_star_menu with your flutter_flow_chart package. Thank you for your extraordinary effort.
But when I try to change the value of a TextField widget inside of a StarMenu I'm encountering this error. I don't know how to solve this. Can you help me with this issue?

`
======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
Cannot get renderObject of inactive element.

> In order for an element to have a valid renderObject, it must be active, which means it is part of the tree.
> Instead, this element is in the _ElementLifecycle.defunct state.
> If you called this method from a State object, consider guarding it with State.mounted.
> The findRenderObject() method was called for the following element: StatefulElement#a8d55(DEFUNCT)
>   no widget
> When the exception was thrown, this was the stack: 
> #0      Element.findRenderObject.<anonymous closure> (package:flutter/src/widgets/framework.dart:4581:9)
> #1      Element.findRenderObject (package:flutter/src/widgets/framework.dart:4594:6)
> #2      StarMenuState._showMenu (package:star_menu/src/star_menu.dart:398:36)
> #3      StarMenuState.showMenu (package:star_menu/src/star_menu.dart:386:7)
> #4      StarMenuState.resetForChanges (package:star_menu/src/star_menu.dart:244:7)
> #5      StarMenuState.didChangeMetrics.<anonymous closure> (package:star_menu/src/star_menu.dart:229:7)
> #6      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1325:15)
> #7      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1264:9)
> #8      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1113:5)
> #9      _invoke (dart:ui/hooks.dart:312:13)
> #10     PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:383:5)
> #11     _drawFrame (dart:ui/hooks.dart:283:31)

====================================================================================================
E/flutter (28082): [ERROR:flutter/runtime/dart_vm_initializer.cc(41)] Unhandled Exception: 'package:flutter/src/widgets/overlay.dart': Failed assertion: line 168 pos 12: '_overlay != null': is not true.
E/flutter (28082): #0      _AssertionError._doThrowNew (dart:core-patch/errors_patch.dart:51:61)
E/flutter (28082): #1      _AssertionError._throwNew (dart:core-patch/errors_patch.dart:40:5)
E/flutter (28082): #2      OverlayEntry.remove (package:flutter/src/widgets/overlay.dart:168:12)
E/flutter (28082): #3      StarMenuState._dispose (package:star_menu/src/star_menu.dart:207:19)
E/flutter (28082): #4      StarMenuState.closeMenu.<anonymous closure> (package:star_menu/src/star_menu.dart:362:9)
E/flutter (28082): #5      Future._propagateToListeners.handleValueCallback (dart:async/future_impl.dart:846:45)
E/flutter (28082): #6      Future._propagateToListeners (dart:async/future_impl.dart:875:13)
E/flutter (28082): #7      Future._completeWithValue (dart:async/future_impl.dart:647:5)
E/flutter (28082): #8      Future._asyncCompleteWithValue.<anonymous closure> (dart:async/future_impl.dart:721:7)
E/flutter (28082): #9      _microtaskLoop (dart:async/schedule_microtask.dart:40:21)
E/flutter (28082): #10     _startMicrotaskLoop (dart:async/schedule_microtask.dart:49:5)
E/flutter (28082): 

======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
Cannot get renderObject of inactive element.

> In order for an element to have a valid renderObject, it must be active, which means it is part of the tree.
> Instead, this element is in the _ElementLifecycle.defunct state.
> If you called this method from a State object, consider guarding it with State.mounted.
> The findRenderObject() method was called for the following element: StatefulElement#a8d55(DEFUNCT)
>   no widget
> When the exception was thrown, this was the stack: 
> #0      Element.findRenderObject.<anonymous closure> (package:flutter/src/widgets/framework.dart:4581:9)
> #1      Element.findRenderObject (package:flutter/src/widgets/framework.dart:4594:6)
> #2      StarMenuState._showMenu (package:star_menu/src/star_menu.dart:398:36)
> #3      StarMenuState.showMenu (package:star_menu/src/star_menu.dart:386:7)
> #4      StarMenuState.build.<anonymous closure> (package:star_menu/src/star_menu.dart:286:9)
> #5      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1325:15)
> #6      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1264:9)
> #7      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1113:5)
> #8      _invoke (dart:ui/hooks.dart:312:13)
> #9      PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:383:5)
> #10     _drawFrame (dart:ui/hooks.dart:283:31)

====================================================================================================
D/InputMethodManager(28082): HSIFW - flag : 0
D/InsetsSourceConsumer(28082): setRequestedVisible: visible=false, type=13, host=com.digitstudios.algorithm/com.digitstudios.algorithm.MainActivity, from=android.view.InsetsSourceConsumer.hide:236 android.view.ImeInsetsSourceConsumer.hide:101 android.view.InsetsController.hideDirectly:1430 android.view.InsetsController.controlAnimationUnchecked:1112 android.view.InsetsController.applyAnimation:1417 android.view.InsetsController.hide:984 android.view.ViewRootImpl$ViewRootHandler.handleMessage:6150 android.os.Handler.dispatchMessage:106 android.os.Looper.loop:246 android.app.ActivityThread.main:8653 
D/InputConnectionAdaptor(28082): The input method toggled cursor monitoring off
I/SurfaceControl(28082): nativeRelease nativeObject s[505567771040]
I/SurfaceControl(28082): nativeRelease nativeObject e[505567771040]

======== Exception caught by scheduler library =====================================================
The following assertion was thrown during a scheduler callback:
Cannot get renderObject of inactive element.

> In order for an element to have a valid renderObject, it must be active, which means it is part of the tree.
> Instead, this element is in the _ElementLifecycle.defunct state.
> If you called this method from a State object, consider guarding it with State.mounted.
> The findRenderObject() method was called for the following element: StatefulElement#a8d55(DEFUNCT)
>   no widget
> When the exception was thrown, this was the stack: 
> #0      Element.findRenderObject.<anonymous closure> (package:flutter/src/widgets/framework.dart:4581:9)
> #1      Element.findRenderObject (package:flutter/src/widgets/framework.dart:4594:6)
> #2      StarMenuState._showMenu (package:star_menu/src/star_menu.dart:398:36)
> #3      StarMenuState.showMenu (package:star_menu/src/star_menu.dart:386:7)
> #4      StarMenuState.build.<anonymous closure> (package:star_menu/src/star_menu.dart:286:9)
> #5      SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1325:15)
> #6      SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1264:9)
> #7      SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:1113:5)
> #8      _invoke (dart:ui/hooks.dart:312:13)
> #9      PlatformDispatcher._drawFrame (dart:ui/platform_dispatcher.dart:383:5)
> #10     _drawFrame (dart:ui/hooks.dart:283:31)

====================================================================================================
`

**Comment by alnitak** [comment]
I think the problem you are facing is because the virtual keyboard on mobile devices, triggers a refresh to the StarMenu. [Here](https://github.com/alnitak/flutter_star_menu/issues/9#issuecomment-1364556698) the issue.
Honestly, I don't know (yet?) how to resolve it!!
I am open to suggestions!
