### ISSUE TITLE
Menu position incorrect

### ISSUE THREAD

**Issue by qasim90** [alnitak/flutter_star_menu#6]
I'm trying to show menu on ListTile widget inside ListView but the menu always appear at the edge (right edge in my case) of the screen and not originated from click location like in example. Specificallly the y coordinate is changing but looks like the x coordinate is ignored. Any clue what's wrong here? Here's is my attempt:
```
StarMenu(
      params: StarMenuParameters(
          // useScreenCenter: true,
          shape: MenuShape.linear,
          linearShapeParams: LinearShapeParams(angle: 270, space: 10, alignment: LinearAlignment.center),
          onItemTapped: (index, ctrllr) => onAyahMenuClick(ayah, index, ctrllr)),
      items: createAyahMenu(),
      child: ListTile(
        // onTap: () => print('clicked'),
        title: Text(ayah.ayahText + ' {${ayah.ayahNumInSurah}} ',
            style: TextStyle(height: 1.8, color: Colors.black, fontSize: controller.fontSize.value)),
        subtitle: ayah.tafseer == null
            ? null
            : Text(ayah.tafseer!,
                textAlign: controller.currTafseer == 'engTafseer' ? TextAlign.left : TextAlign.right,
                style: TextStyle(height: 1.8, color: Colors.green, fontSize: controller.fontSize.value - 3)),
      ),
    )
```
![Simulator Screen Shot - iPhone 12 - 2022-03-09 at 12 28 17](https://user-images.githubusercontent.com/37286802/157394523-8343c52b-9d35-434b-8c6f-95a5ae1d3725.png)

**Comment by alnitak** [comment]
Hi,
I think the best way is to use a `leading` inside the `ListTile` where you can put `StarMenu`:

```
ListTile(
    ...
    leading: StarMenu(
                   ...
                    child: Icon(...),
     ),
)
```

or maybe put `StarMenu` as a parent of the Text of your `title`

**Comment by qasim90** [comment]
Thanks for quick reply.

> or maybe put StarMenu as a parent of the Text of your title

Tried this but didn't work. Stays the same. Is it mandatory to always use `ScrollView` like in example because I see the example works perfectly?

**Comment by alnitak** [comment]
`ScrollView` is not mandatory. When StarMenu opens, the parent position is taken as the center of menu items.
If you have a minimal example I can try to look at it.
Or maybe you wish to start drawing the menu items from the ListTile:
`alignment: LinearAlignment.center` will center the entire menu at the center of parent
`alignment: LinearAlignment.bottom` will start drawing menu items from the first at the center of the parent

**Comment by qasim90** [comment]
Ok, looks like the problem is mainly due to `rtl` direction as the menu appears in center of the screen when `GlobalWidgetsLocalizations.delegate` is commented in `MaterialApp` (which provides `rtl` support). I've created a sample test case here: https://github.com/qasim90/StarMenuTest 
The test case also includes an implementation with `TextSpan`s and Scrollview. When using this you'd see the menu always appear at the bottom of the screen and ignoring click origin.

**Comment by alnitak** [comment]
you are right, the `rtl` is the problem. I fixed that forcing the `ltr` in the root widget of the overlay menu. I didn't find a solution to get the right position and size obtained using `RenderObject`. 
Thanks for finding this bug and for the test sources you made! Please try it, it should be already available on pub.dev (now with version ^2.1.2) and of course here.
