### ISSUE TITLE
Open on long press?

### ISSUE THREAD

**Issue by alexursul** [alnitak/flutter_star_menu#7]
Hello! Thank you for the great component! Is it possible to open a menu on long press?

**Comment by alnitak** [comment]
Hi @alexursul ,

unfortunately I used Listener to grab touches which doesn't have the long press trigger. But with a trick I added in the [StarMenu.params] the [useLongpress] and [longPressDuration]. 
The defaultvalues are:
useLongpress=false
longPressDuration=Duration(milliseconds: 500)
So you should enable it to try.
Enjoy!
